# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatAppFinished' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatAppFinished

	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'

  target 'ChatAppFinishedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatAppFinishedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
